# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# you can replace it with "." if you want the root to be the current working directory
root_dir: ${oc.env:PROJECT_ROOT}

# path to data directory
data_dir: ${paths.root_dir}/data/

# path to logging directory
log_dir: ${paths.root_dir}/logs/

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}

# path to working directory
work_dir: ${hydra:runtime.cwd}

subset2episode: bobsl/cslr_annotation/bobsl/splits/subset2episode.json #
vocab_pkl: bobsl/cslr_annotation/bobsl/vocab/8697_vocab.pkl
info_pkl: bobsl/cslr_annotation/bobsl/unannotated-info/info-src_videos_2236.pkl
annotations_pkl: bobsl/cslr_annotation/bobsl/lmdbs/lmdb-pl_vswin_t-bs256_float16/
vid_features_lmdb: bobsl/cslr_annotation/bobsl/lmdbs/lmdb-feats_vswin_t-bs256_float16/
subtitles_path: bobsl/cslr_annotation/bobsl/subtitles_pkl/best_delta_postpro_bobsl_best_traineval_0_pslab_ftune_.pkl
aligned_subtitles_path: bobsl/cslr_annotation/bobsl/subtitles_pkl/manually-aligned.pkl
synonyms_pkl: bobsl/cslr_annotation/bobsl/syns/synonym_pickle_english_and_signdict_and_signbank.pkl
llm_root: Meta-Llama-3-8B
bleurt_path: lucadiliello/BLEURT-20
blip_cap_path: ./blip2_captions_v2.pkl
val_episode_ind_path: ./val_start_indices.json
test_episode_ind_path: ./test_start_indices.json
train_cap_path: ./prev_gt_captions.json
spottings_path: null