# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# you can replace it with "." if you want the root to be the current working directory
root_dir: ${oc.env:PROJECT_ROOT}

# path to data directory
data_dir: ${paths.root_dir}/data/

# path to logging directory
log_dir: ${paths.root_dir}/logs/

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}

# path to working directory
work_dir: ${hydra:runtime.cwd}

subset2episode: /mnt/lynx2/datasets/how2sign/split/subset2episode.json # checked
vocab_pkl: /mnt/lynx2/datasets/how2sign/vocab/c1887.pkl # checked
info_pkl: /mnt/lynx2/datasets/how2sign/info/info-src_videos_2528.pkl # checked
annotations_pkl: /mnt/lynx2/datasets/how2sign/lmdbs/new_swin_prebobsl_large/pseudo_labels
vid_features_lmdb: /mnt/lynx2/datasets/how2sign/lmdbs/new_swin_prebobsl_large/features
word_embds_pkl: /mnt/lynx2/datasets/bobsl/bobsl/cslr_annotation/bobsl/vocab_embds/t5-large_8k_word_embeddings.pkl # not used
subtitles_path: /mnt/lynx2/datasets/how2sign/subtitle/realigned_subtitles.pkl # 
aligned_subtitles_path: /mnt/lynx2/datasets/how2sign/subtitle/realigned_subtitles.pkl #
synonyms_pkl: /mnt/lynx2/datasets/bobsl/bobsl/cslr_annotation/bobsl/syns/synonym_pickle_english_and_signdict_and_signbank.pkl
rgb_frames: null
llm_root: /mnt/bear1/users/jyj/VGG/lamma3/Meta-Llama-3-8B
lm_root: ../cslr2/t5_checkpoint/
question_pool: ./data/question_pool.txt
cslr2_ckpt: model_best.pth
bleurt_path: lucadiliello/BLEURT-20
pl_dist_path: null #./add_files/pl_dist.pkl
blip_cap_path: null
val_episode_ind_path: /mnt/lynx2/datasets/how2sign/index/val_how2sign_indices.json
test_episode_ind_path: /mnt/lynx2/datasets/how2sign/index/test_how2sign_indices.json
man_gloss_path: null #../cslr2_t/bobsl/manual_gloss/dense_annotations.06.09.24/
train_sent_ret_path: null
val_sent_ret_path: null
lip_feats_path: nononononono
train_cap_path: null
spottings_path: null
