# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# you can replace it with "." if you want the root to be the current working directory
root_dir: ${oc.env:PROJECT_ROOT}

# path to data directory
data_dir: ${paths.root_dir}/data/

# path to logging directory
log_dir: ${paths.root_dir}/logs/

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}

# path to working directory
work_dir: ${hydra:runtime.cwd}

subset2episode: /lustre/fswork/projects/rech/vvh/upk96qz/datasets/How2Sign/split/split/subset2episode.json # checked
vocab_pkl: /lustre/fswork/projects/rech/vvh/upk96qz/datasets/How2Sign/vocab/vocab/c1887.pkl # checked
info_pkl: /lustre/fswork/projects/rech/vvh/upk96qz/datasets/How2Sign/info/info/info-src_videos_2528.pkl # checked
annotations_pkl: /lustre/fswork/projects/rech/vvh/upk96qz/datasets/How2Sign/lmdbs/new_swin_prebobsl_large/pseudo_labels 
# vid_features_lmdb: /mnt/lynx4/datasets/how2sign/lmdbs/lmdb--feats_i3d_how2sign-how2sign
vid_features_lmdb: /lustre/fswork/projects/rech/vvh/upk96qz/datasets/How2Sign/lmdbs/new_swin_prebobsl_large/features
word_embds_pkl: ../cslr2_t/bobsl/vocab_embds/t5-large_8k_word_embeddings.pkl # not used
subtitles_path:  /lustre/fswork/projects/rech/vvh/upk96qz/datasets/How2Sign/subtitle/realigned_id_sub.pkl # 
aligned_subtitles_path:  /lustre/fswork/projects/rech/vvh/upk96qz/datasets/How2Sign/subtitle/realigned_id_sub.pkl
synonyms_pkl: ../cslr2_t/bobsl/syns/synonym_pickle_english_and_signdict_and_signbank.pkl
rgb_frames: null
llm_root: ../hf/Meta-Llama-3-8B
lm_root: ../cslr2_t/t5_checkpoint/
question_pool: ./data/question_pool.txt
cslr2_ckpt: ../cslr2_t/hrn_reproduce_withmask_4G/models/model_best.pth
bleurt_path: ../hf/BLEURT-20
pl_dist_path: null #./add_files/pl_dist.pkl
blip_cap_path: null
val_episode_ind_path: /lustre/fswork/projects/rech/vvh/upk96qz/datasets/How2Sign/index/index/val_how2sign_indices.json
test_episode_ind_path: /lustre/fswork/projects/rech/vvh/upk96qz/datasets/How2Sign/index/index/test_how2sign_indices.json

man_gloss_path: null #../cslr2_t/bobsl/manual_gloss/dense_annotations.06.09.24/
train_sent_ret_path: ../cslr2_t/bobsl/train_sent_ret.pkl
val_sent_ret_path: ../cslr2_t/bobsl/val_sent_ret.pkl
lip_feats_path: nononononono
train_cap_path: h2s_feats_plsb50_train_cap.json
spottings_path: null